// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRedSwitchChange();
void onBlueLedSwitchChange();

CloudDimmedLight red_switch;
CloudTemperatureSensor temp;
CloudRelativeHumidity humidity;
bool blue_led_switch;
bool motion_thing;

void initProperties(){

  ArduinoCloud.addProperty(red_switch, READWRITE, ON_CHANGE, onRedSwitchChange);
  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(blue_led_switch, READWRITE, ON_CHANGE, onBlueLedSwitchChange);
  ArduinoCloud.addProperty(motion_thing, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);